-- Чат только для двух соперников по матчу (уникальный на каждый матч).
-- Выполни в Supabase → SQL Editor после создания таблицы matches.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  sender_id uuid not null references public.players(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_messages_match_id on public.chat_messages(match_id);
create index if not exists idx_chat_messages_created_at on public.chat_messages(match_id, created_at);

alter table public.chat_messages enable row level security;

-- anon может читать и писать сообщения (доступ к чату матча проверяется на уровне приложения)
create policy "chat_messages anon select" on public.chat_messages
  for select to anon using (true);

create policy "chat_messages anon insert" on public.chat_messages
  for insert to anon with check (true);

comment on table public.chat_messages is 'Сообщения чата между двумя игроками по матчу (один чат = один матч)';

-- Для мгновенной доставки сообщений включи Realtime для таблицы:
-- Supabase Dashboard → Database → Replication → включи публикацию для public.chat_messages
