-- Чат только для двух соперников по турнирному матчу (уникальный на каждый матч).
-- Выполни в Supabase → SQL Editor после создания таблицы tournament_matches.

create table if not exists public.tournament_match_chat_messages (
  id bigint generated by default as identity primary key,
  tournament_match_id uuid not null references public.tournament_matches(id) on delete cascade,
  sender_id uuid not null references public.players(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_tournament_match_chat_tournament_match_id on public.tournament_match_chat_messages(tournament_match_id);
create index if not exists idx_tournament_match_chat_created_at on public.tournament_match_chat_messages(tournament_match_id, created_at);

alter table public.tournament_match_chat_messages enable row level security;

-- anon может читать и писать (доступ к чату матча проверяется на уровне приложения, как у chat_messages)
create policy "tournament_match_chat anon select" on public.tournament_match_chat_messages
  for select to anon using (true);

create policy "tournament_match_chat anon insert" on public.tournament_match_chat_messages
  for insert to anon with check (true);

comment on table public.tournament_match_chat_messages is 'Сообщения чата между двумя игроками по турнирному матчу (один чат = один tournament_match)';

-- Realtime: новые сообщения приходят без перезагрузки
alter publication supabase_realtime add table public.tournament_match_chat_messages;
